# Generated by Django 6.0.1 on 2026-01-07 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PAFImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='paf_imports/')),
                ('year', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PAFAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acao', models.CharField(max_length=30)),
                ('area_atuacao', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('tipo_produto', models.CharField(max_length=250)),
                ('indicador', models.CharField(max_length=250)),
                ('meta', models.CharField(max_length=250)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='VIGENTE', max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidade_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paf_actions', to='paf.unidadetecnica')),
            ],
            options={
                'unique_together': {('codigo_acao', 'ano')},
            },
        ),
    ]
