# Generated by Django 6.0.1 on 2026-01-08 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('esfera', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPortariaFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=80)),
                ('sigla_status', models.CharField(max_length=80)),
                ('ordem_exibicao', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='TipoFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('situacao_tipo_fiscalizacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPortaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('situacao_tipo_portaria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortariaFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portaria', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('numero_processo_sei', models.CharField(max_length=50)),
                ('ano_processo_sei', models.CharField(max_length=4)),
                ('objetivo', models.TextField()),
                ('deliberacao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('portaria_revogada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.portariafiscalizacao')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portarias_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portarias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portaria_fiscalizacao',
            },
        ),
        migrations.CreateModel(
            name='PortariaFiscalizacaoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.entidade')),
                ('portaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.portariafiscalizacao')),
            ],
            options={
                'db_table': 'portaria_fiscalizacao_entidade',
            },
        ),
        migrations.AddField(
            model_name='portariafiscalizacao',
            name='entidades',
            field=models.ManyToManyField(blank=True, through='portaria.PortariaFiscalizacaoEntidade', to='portaria.entidade'),
        ),
        migrations.AddField(
            model_name='portariafiscalizacao',
            name='status_portaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.statusportariafiscalizacao'),
        ),
        migrations.AddField(
            model_name='portariafiscalizacao',
            name='tipo_fiscalizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.tipofiscalizacao'),
        ),
        migrations.AddField(
            model_name='portariafiscalizacao',
            name='tipo_portaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.tipoportaria'),
        ),
    ]
